# Generated by Django 4.1.7 on 2023-02-23 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogcomment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 10, 5, 33, 701649, tzinfo=datetime.timezone.utc), verbose_name='Дата коммента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 16, 5, 33, 701186), verbose_name='Дата публикации'),
        ),
    ]
