# Generated by Django 4.1.7 on 2023-02-23 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogcomment_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 10, 20, 22, 792826, tzinfo=datetime.timezone.utc), verbose_name='Дата коммента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 16, 20, 22, 792330), verbose_name='Дата публикации'),
        ),
    ]
