# Generated by Django 4.1.7 on 2023-02-23 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blogcomment_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 11, 37, 16, 978381, tzinfo=datetime.timezone.utc), verbose_name='Дата коммента'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 17, 37, 16, 977895), verbose_name='Дата публикации'),
        ),
    ]
