# Generated by Django 4.1.7 on 2023-02-23 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 16, 5, 33, 703915)),
        ),
    ]
